### ISSUE TITLE
BSL Licence = Free 2 use ?

### ISSUE THREAD

**Issue by konstantinkrassmann** [Delapouite/JsClipper#4]
Hello ! 

My company is currently building an application with threejs and because of some clipping problem, we were looking for a library like jsclipper. 

But we are not sure, if we can use it in our project, because the BSL licence limitations are not really clear. 

We won't modify it, just use for some intersection calculations. 

Nowdays every lib is under MIT. 

Can you clear out the limitations of use ?

**Comment by Delapouite** [comment]
Hi.

I understand your concern. Here are the terms of the Boost Software License :
http://opensource.org/licenses/BSL-1.0

I'm not a lawyer by any mean but it appears that this license isn't really restrictive.
You may want to reach the original developer on the source forge project for further details.

On a side note, be aware that I forked it for specific purpose but I can't  unfortunately offer you any waranty nor support over this project.

**Comment by konstantinkrassmann** [comment]
Thank for your answer, i will contact the author then thx.
